### ISSUE TITLE
Sprint 7 Review

### ISSUE THREAD

**Issue by histtranger** [juliett-golf-hotel/web-app#60]

**Comment by histtranger** [comment]
I finished my small task really quickly. I had no real problems, so I'd say it was really successful. I only had 1 task to do, which was throwing the cards I made into the index.html file.

**Comment by geni97** [comment]
This week's sprint went well. My job was to add the illustrative banner into the website, and add the information that will show up on the banner. I finished these tasks with only some small issues that were resolved in class.

**Comment by hldouglas** [comment]
This week was minor changes and getting all the content to work together. I made small aesthetic changes to a few pages so that I could help with all the errors and issues my team might run into. I helped figure out a way to make the hero banner appear at different sizes in the browser.

**Comment by hldouglas** [comment]
@thomasjbradley
