### ISSUE TITLE
Sprint 8 Review

### ISSUE THREAD

**Issue by histtranger** [juliett-golf-hotel/web-app#61]

**Comment by hldouglas** [comment]
User testing and browser testing went well. The feedback we got was that is was cute and easy to use. Browser testing was done near perfectly with a couple outliers (see the browser testing issue). This project went very well and was well received.

**Comment by histtranger** [comment]
It went really well, the website displayed nicely on my phone and in my browsers. A lot of users said they found it cute and really easy to use.

**Comment by geni97** [comment]
Sprint 8 went well, we user tested our app and everyone told us it's easy to use. We browser tested which also went really well with very minor issues.

**Comment by hldouglas** [comment]
@thomasjbradley
