### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by histtranger** [juliett-golf-hotel/web-app#62]
Make sure it works on 
- [x] All screen sizes (small, medium, large)
- [x] Test across browsers (safari, opera, firefox, chrome) on desktop
- [x] Test across browsers (chrome, phone browser) on mobile

**Comment by hldouglas** [comment]
Safari makes an unwanted boldness to the text.
Geni's phone browser doesn't show colours or fonts.
Everything appears fine.
